# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 23:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('light_level', models.IntegerField()),
                ('soil_moisture', models.IntegerField()),
                ('nutrient_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(default='', max_length=1024, unique=True)),
                ('device_type', models.SmallIntegerField(choices=[(1, 'Android'), (2, 'iPhone'), (3, 'Chrome'), (4, 'Other')])),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gnome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GnomeFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='GnomeModel',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('features', models.ManyToManyField(to='tracker.GnomeFeature')),
            ],
        ),
        migrations.AddField(
            model_name='gnome',
            name='gnome_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.GnomeModel'),
        ),
        migrations.AddField(
            model_name='gnome',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gnomes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataset',
            name='gnome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='tracker.Gnome'),
        ),
    ]
